version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    volumes:
      - ./uploads:/app/api/uploads
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - backend
  db:
    image: postgres:15-alpine
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  minio:
    image: minio/minio:latest
    command: server /data --console-address :9001
    env_file: .env
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
volumes:
  db_data:
  minio_data:
